[ART]
title = "Art Options"

[ART."Content.Aware.Fill"]
title = "Content Aware Fill"
desc = """When enabled, the area not covered by the source image is filled using Content Aware Fill."""
type = "bool"
default = 1

[COLORS]
title = "Color Options"

[COLORS."Max.Colors"]
title = "Max Frame Colors"
desc = """How many colors can the frame split by before the card just becomes Gold?"""
type = "options"
default = "2"
options = ["1", "2", "3", "4", "5"]

[COLORS."Front.Face.Colors"]
title = "Authentic Front Face Colors"
desc = """When enabled, front face MDFC and Transform cards will have authentic lighter colors."""
type = "bool"
default = 1

[COLORS."Multicolor.Pinlines"]
title = "Multicolor Pinlines"
desc = """When enabled, the Pinlines on multicolor cards will use blended colors instead of Gold."""
type = "bool"
default = 1

[COLORS."Pinlines.Override"]
title = "Pinlines color override"
desc = """Override pinline colors with given colors. Specify as a list of hex color codes separated by commas, e.g. '#ffffff,#000000'."""
type = "string"
default = ""

[COLORS."Expansion.Symbol.Override"]
title = "Expansion symbol color override"
desc = """Override expansion symbol color gradient."""
type = "options"
options = ["Off", "Identity", "Pinlines override", "Custom"]
default = "Off"

[COLORS."Expansion.Symbol.Custom"]
title = "Expansion symbol custom colors"
desc = """Custom colors for expansion symbol. Specify as a list of hex color codes separated by commas, e.g. '#ffffff,#000000'."""
type = "string"
default = ""

[COLORS."Expansion.Symbol.Darken"]
title = "Darken expansion symbol gradient ends"
desc = """Darkens the first and last override color in the expansion symbol gradient. Specify as a value between 0-100."""
type = "numeric"
default = 0.0

[COLORS."Expansion.Symbol.Angle"]
title = "Expansion symbol gradient angle"
desc = """The angle to use for the expansion symbol color gradient. Specify as a value between -360-360."""
type = "numeric"
default = -45.0

[COLORS."Expansion.Symbol.Scale"]
title = "Expansion symbol gradient scale"
desc = """The scale to use for the expansion symbol color gradient. Specify as a value between 10-150."""
type = "numeric"
default = 70.0

[COLORS."Expansion.Symbol.Method"]
title = "Expansion symbol gradient method"
desc = """The method to use for the expansion symbol color gradient."""
type = "options"
options = ["perceptual", "linear", "classic", "smooth", "stripes"]
default = "linear"

[TEXT]
title = "Text Options"

[TEXT."Textbox.Height"]
title = "Textbox height"
desc = """The height to use for the textbox in pixels. Values <= 0 disable this setting.
For reference, the height options that the normal Borderless template uses are:
Tall = 1230
Normal = 1046
Medium = 866
Short = 661
"""
type = "numeric"
default = 0.0

[TEXT."Rules.Text.Font.Size"]
title = "Rules text font size"
desc = "Font size in points to use for rules text, excluding Case, Class, Saga and Planeswalker layouts. The textbox is automatically sized to conform to the chosen font size. This setting overrides the 'Textbox height' setting. Values <= 0 disable this setting."
type = "numeric"
default = 0.0

[TEXT."Rules.Text.Padding"]
title = "Rules text vertical padding"
desc = "The amount of extra vertical padding in pixels to add to rules text. Applies to Planeswalker cards and to other cards when using 'Rules text font size' setting."
type = "numeric"
default = 64.0

[TEXT.Nickname]
title = "Use Nickname"
desc = """When enabled, card will be rendered with both a 'real' name and a 'nickname' you can enter manually."""
type = "bool"
default = 0

[TEXT."Vertical.Reminder"]
title = "Saga/Class Reminder"
desc = """When enabled, the Saga/Class reminder text is displayed."""
type = "bool"
default = 1

[SHAPES]
title = "Shape Options"

[SHAPES."PT.Box.And.Pinline"]
title = "PT Box and Bottom Pinline"
desc = """The type of the Power and Toughness Box and Bottom Pinline."""
type = "options"
default = "Full"
options = ["Full", "Partial", "Split"]

[SHAPES."Bottom.Border"]
title = "Bottom Border"
desc = """The type of the bottom border."""
type = "options"
default = "Full"
options = ["Full", "Fade", "Shadow", "None"]

[SHAPES."Flip.Twins"]
title = "Flip Name and Type Pinlines Horizontally"
desc = """When enabled, flips name and type pinlines horizontally. Mainly meant to make the layout look neater without a Set symbol."""
type = "bool"
default = 0

[BACKUP]
title = "Backup Options"

[BACKUP."Save"]
title = "Save a backup"
desc = "When enabled, saves a partial backup of the rendered template. Mainly meant to preserve popouts."
type = "bool"
default = 0

[BACKUP."Load"]
title = "Load a backup"
desc = "When enabled, asks to pick a backup file from which backed up data, e.g. art, is loaded."
type = "bool"
default = 0

[BACKUP."Directory"]
title = "Backup directory"
desc = "The path to a directory to which backups are saved to and loaded from. Defaults to './backup' when no set."
type = "string"
default = ""

[BACKUP."Art.Prompt"]
title = "Prompt to save art layer"
desc = "When enabled, asks if the art layer should be copied to the backup."
type = "bool"
default = 0

[OTHER]
title = "Other Options"

[OTHER."Copy.Art"]
title = "Copy art from backup (deprecated)"
desc = "When enabled, copies artwork and channels from a chosen backup template."
type = "bool"
default = 0
