name: Release
on:
  push:
    branches: ["main"]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Build
        run: |
          npm install
          npm run build

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Set current path friendly date as env variable
        run: echo "NOW_PATH=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Set commit short sha as env variable
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Set release archive name as env variable
        run: echo "ARCHIVE_NAME=${GITHUB_REPOSITORY#*/}_${NOW_PATH}_${SHORT_SHA}.zip" >> $GITHUB_ENV

      - name: Package
        run: |
          mkdir proxy_stuff
          cp -r config dist py LICENSE manifest.yml README.md proxy_stuff
          zip -r "./${ARCHIVE_NAME}" proxy_stuff

      - name: Create release tag
        run: |
          git tag -f ${NOW}
          git push origin ${NOW}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.NOW }}-${{ env.SHORT_SHA }}"
          files: ${{ env.ARCHIVE_NAME }}
          tag_name: ${{ env.NOW }}
          fail_on_unmatched_files: true
          generate_release_notes: true
